name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        go-version: ['1.21']  # Add more Go versions if needed
        arch: ['amd64', 'arm64']  # Add more architectures if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        arch: ${{ matrix.arch }}

    - name: Debug Matrix Values
      run: |
        echo "go-version: ${{ matrix.go-version }}"
        echo "arch: ${{ matrix.arch }}"

    - name: Build
      run: go build -o tty-cleaner ./cmd/mac-tty-cleaner

    - name: Upload Build Artifact (amd64)
      if: matrix.go-version == '1.21' && matrix.arch == 'amd64'
      uses: actions/upload-artifact@v3
      with:
        name: tty-cleaner-amd64
        path: ./tty-cleaner

    - name: Upload Build Artifact (arm64)
      if: matrix.go-version == '1.21' && matrix.arch == 'arm64'
      uses: actions/upload-artifact@v3
      with:
        name: tty-cleaner-arm64
        path: ./tty-cleaner
